#!/usr/bin/env python3
"""
One-time setup script: creates the 6 GMMBB pillar notebooks in NotebookLM
and writes their IDs to .env.notebooklm.

Run once after first authenticating with `notebooklm login` (or setting
NOTEBOOKLM_AUTH_JSON for headless environments).

Usage:
    python scripts/setup_notebooklm.py [--profile muscle-meta] [--dry-run]
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

PILLARS = [
    {
        "env_key": "NOTEBOOKLM_NB_GUT",
        "title": "MuscleMeta: Gut Health",
        "starter_query": "gut microbiome muscle mass sarcopenia aging",
    },
    {
        "env_key": "NOTEBOOKLM_NB_MUSCLE",
        "title": "MuscleMeta: Muscle Mass",
        "starter_query": "sarcopenia resistance training protein synthesis aging",
    },
    {
        "env_key": "NOTEBOOKLM_NB_METABOLISM",
        "title": "MuscleMeta: Metabolism",
        "starter_query": "metabolic rate insulin resistance aging muscle",
    },
    {
        "env_key": "NOTEBOOKLM_NB_BONE",
        "title": "MuscleMeta: Bone Health",
        "starter_query": "bone density vitamin D calcium osteoporosis prevention",
    },
    {
        "env_key": "NOTEBOOKLM_NB_BRAIN",
        "title": "MuscleMeta: Brain Function",
        "starter_query": "neuroplasticity cognitive decline exercise aging",
    },
    {
        "env_key": "NOTEBOOKLM_NB_CONNECTIONS",
        "title": "MuscleMeta: GMMBB Connections",
        "starter_query": "catabolic decline GMMBB gut brain muscle axis aging",
    },
]

ENV_FILE = Path(".env.notebooklm")


def run(cmd: list[str], check: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, capture_output=True, text=True, check=check)


def load_existing_env() -> dict[str, str]:
    """Read existing .env.notebooklm if it exists."""
    if not ENV_FILE.exists():
        return {}
    existing: dict[str, str] = {}
    for line in ENV_FILE.read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#") and "=" in line:
            k, _, v = line.partition("=")
            existing[k.strip()] = v.strip()
    return existing


def write_env(env: dict[str, str]) -> None:
    lines = [
        "# NotebookLM notebook IDs for MuscleMeta GMMBB pillars",
        "# Auto-generated by scripts/setup_notebooklm.py — do not edit manually",
        "",
        f"NOTEBOOKLM_PROFILE={env.get('NOTEBOOKLM_PROFILE', 'muscle-meta')}",
        "",
        "# GMMBB Pillar Notebook IDs",
    ]
    for pillar in PILLARS:
        key = pillar["env_key"]
        lines.append(f"{key}={env.get(key, '')}")
    ENV_FILE.write_text("\n".join(lines) + "\n")


def create_notebook(title: str, profile: str | None, dry_run: bool) -> str | None:
    cmd = ["notebooklm"]
    if profile:
        cmd += ["-p", profile]
    cmd += ["create", title, "--json"]

    if dry_run:
        print(f"  [dry-run] Would run: {' '.join(cmd)}")
        return f"dry-run-id-{title.split()[-1].lower()}"

    result = run(cmd, check=False)
    if result.returncode != 0:
        print(f"  ERROR creating '{title}': {result.stderr.strip()}", file=sys.stderr)
        return None

    try:
        data = json.loads(result.stdout)
        return data.get("id") or data.get("notebook_id")
    except json.JSONDecodeError:
        # Some versions output plain ID on a line
        first_line = result.stdout.strip().splitlines()[0] if result.stdout.strip() else ""
        if first_line and len(first_line) > 8:
            return first_line
        print(f"  ERROR: could not parse notebook ID from: {result.stdout!r}", file=sys.stderr)
        return None


def seed_research(notebook_id: str, query: str, profile: str | None, dry_run: bool) -> None:
    cmd = ["notebooklm"]
    if profile:
        cmd += ["-p", profile]
    cmd += ["source", "add-research", query, "-n", notebook_id, "--mode", "fast", "--no-wait"]

    if dry_run:
        print(f"  [dry-run] Would seed research: {query!r}")
        return

    result = run(cmd, check=False)
    if result.returncode != 0:
        print(f"  WARNING: could not seed research for {notebook_id}: {result.stderr.strip()}")
    else:
        print(f"  Seeded research (fast mode, background): {query!r}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Set up MuscleMeta NotebookLM notebooks")
    parser.add_argument("--profile", default=os.environ.get("NOTEBOOKLM_PROFILE", "muscle-meta"))
    parser.add_argument("--dry-run", action="store_true", help="Print what would happen, don't create")
    parser.add_argument("--no-seed", action="store_true", help="Skip seeding starter research queries")
    args = parser.parse_args()

    print(f"MuscleMeta NotebookLM Setup (profile: {args.profile})")
    print("=" * 55)

    existing = load_existing_env()
    existing["NOTEBOOKLM_PROFILE"] = args.profile
    created, skipped, failed = 0, 0, 0

    for pillar in PILLARS:
        key = pillar["env_key"]
        title = pillar["title"]
        existing_id = existing.get(key, "").strip()

        if existing_id:
            print(f"  SKIP  {title}  (ID already set: {existing_id[:12]}...)")
            skipped += 1
            continue

        print(f"  CREATE {title} ...", end=" ", flush=True)
        notebook_id = create_notebook(title, args.profile, args.dry_run)
        if notebook_id:
            existing[key] = notebook_id
            print(f"OK ({notebook_id[:12]}...)")
            created += 1
            if not args.no_seed:
                seed_research(notebook_id, pillar["starter_query"], args.profile, args.dry_run)
        else:
            print("FAILED")
            failed += 1

    write_env(existing)
    print()
    print(f"Done. Created: {created}  Skipped: {skipped}  Failed: {failed}")
    print(f"IDs written to: {ENV_FILE}")

    if failed > 0:
        print("\nSome notebooks failed to create. Check auth and retry.", file=sys.stderr)
        sys.exit(1)

    print("\nNext steps:")
    print("  source .env.notebooklm")
    print("  notebooklm list")


if __name__ == "__main__":
    main()
